from . import res_config_settings
from . import res_users
from . import res_company
from . import mail_thread
from . import mail_template
from . import mail_composer
from . import product_template
from . import sale_subscription_plan
from . import sale_order
from . import sale_order_line
from . import license_checkouts
from . import license_downloads
from . import license_keys
from . import account_payment_term
